name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Please tell me what you saw and what you expected to see.
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: What device(s) are you seeing the problem on?
      multiple: true
      options:
        - Desktop
        - Mobile
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Microsoft Edge
        - Safari
        - Firefox
