name: Feature Request
description: Suggest an idea for this project
title: 'Feature: '
labels: ['enhancement']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: What would feature would you like to see added or enhanced?
      description: Please describe what you would like to see and why.
    validations:
      required: true
