name: Deploy

on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm ci
          npm run clean
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload files to S3
        run: |
          aws s3 sync ./dist/personal-site-ngx/ s3://${{ secrets.S3_BUCKET }} --delete

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'No deployment due to failed build.'
